language: c++

branches:
  only:
    - master

dist: bionic

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug BUILD_TESTS=OFF
  - BUILD_TYPE=Debug BUILD_TESTS=ON
  - BUILD_TYPE=Release BUILD_TESTS=OFF
  - BUILD_TYPE=Release BUILD_TESTS=ON

before_install:
  - sudo apt-get update
  # For coverage reports
  - sudo apt-get install -y lcov

install:
  - . ${TRAVIS_BUILD_DIR}/ci/download_cmake.sh 3.15

script:
  - cd ${TRAVIS_BUILD_DIR}
  - . ./ci/build_and_run.sh

after_success:
  # Upload report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
